# Generated by Django 4.1.2 on 2022-11-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('name_per', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('name_account', models.CharField(max_length=15)),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.permission')),
            ],
        ),
    ]
