# Generated by Django 4.1.2 on 2022-11-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='name_account',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
