# Generated by Django 4.1.2 on 2022-11-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_product_id_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
