# Generated by Django 4.1.2 on 2022-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMPs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=15)),
                ('f_name', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('other', 'other'), ('male', 'male'), ('female', 'female')], max_length=6)),
                ('date', models.DateField()),
                ('numberPhone', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
