# Generated by Django 4.1.2 on 2022-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_emps_date_alter_emps_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emps',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
