# Generated by Django 4.1.2 on 2022-11-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_password_alter_account_name_account'),
        ('emp', '0003_emps_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='emps',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
