# Generated by Django 4.1.2 on 2022-11-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_emps_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emps',
            old_name='username',
            new_name='id_account',
        ),
    ]
