# Generated by Django 4.1.2 on 2022-11-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_emps_id_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emps',
            name='id_account',
        ),
    ]
