# Generated by Django 4.1.2 on 2022-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_emps_id_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emps',
            name='id_account',
        ),
        migrations.AddField(
            model_name='emps',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=50, unique=True),
        ),
    ]
