# Generated by Django 4.1.2 on 2022-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_remove_emps_id_account_emps_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emps',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
