# Generated by Django 4.1.2 on 2022-11-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_password_alter_account_name_account'),
        ('emp', '0014_alter_emps_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emps',
            name='id_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account'),
        ),
    ]
