# Generated by Django 4.1.2 on 2022-11-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_products'),
        ('order', '0003_rename_date_orderdetail_date_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id_orderdetail', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('date_orderdetail', models.DateTimeField(auto_now_add=True)),
                ('id_Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdetail', to='order.order')),
                ('id_Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.products')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
